version: 0.0
# AppSpec Configuration for AWS Code Deploy
os: linux 

# Before the application is deployed, Tomcat needs to be stopped and 
# the existing applications cleaned up, otherwise, AWS Codedeploy will not
# overwrite the files. 
hooks:
 ApplicationStop:
   - location: stop-docker.sh
     timeout: 300
     runas: ubuntu
 # Now we can start up Tomcat once again
 ApplicationStart:
   - location: start-docker.sh
     timeout: 600
     runas: ubuntu